# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'util_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_util(object):
    def setupUi(self, util):
        util.setObjectName("util")
        util.resize(268, 217)
        self.centralwidget = QtWidgets.QWidget(util)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(50, 30, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(50, 60, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 100, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 140, 70, 17))
        self.checkBox.setObjectName("checkBox")
        util.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(util)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 268, 21))
        self.menubar.setObjectName("menubar")
        util.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(util)
        self.statusbar.setObjectName("statusbar")
        util.setStatusBar(self.statusbar)

        self.retranslateUi(util)
        QtCore.QMetaObject.connectSlotsByName(util)

    def retranslateUi(self, util):
        _translate = QtCore.QCoreApplication.translate
        util.setWindowTitle(_translate("util", "MainWindow"))
        self.pushButton.setText(_translate("util", "PushButton"))
        self.checkBox.setText(_translate("util", "CheckBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    util = QtWidgets.QMainWindow()
    ui = Ui_util()
    ui.setupUi(util)
    util.show()
    sys.exit(app.exec_())
